#!/bin/bash

set -x

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
cd "$SCRIPT_DIR/.."

# run ruff linter
uv run --directory superverse --dev ruff check --fix ./

# run ruff formatter
uv run --directory superverse --dev ruff format ./

# run dotenv-linter linter
uv run --project superverse --dev dotenv-linter ./superverse/.env.example ./web/.env.example

# run mypy check
dev/mypy-check
