name: ❓ Question
description: Ask a Metavision question
# title: " "
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for asking a Metavision ❓ Question!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/khulnasoft/metavision/issues) to see if a similar feature request already exists.
      options:
        - label: >
            I have searched the Metavision [issues](https://github.com/khulnasoft/metavision/issues) and found no similar feature requests.
          required: true

  - type: textarea
    attributes:
      label: Question
      description: What is your question?
      placeholder: |
        💡 ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?
